---
kind: Namespace
apiVersion: v1
metadata:
  name: flux-system
---
# Source: flux/templates/helm-controller/networkpolicy.yaml
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: flux-helm-controller
  namespace: "flux-system"
  labels:
    app.kubernetes.io/instance: flux
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: flux
    app.kubernetes.io/version: 1.0.1
    helm.sh/chart: flux-2.3.12
    app.kubernetes.io/part-of: flux
    app.kubernetes.io/component: helm-controller
spec:
  policyTypes:
    - Ingress
    - Egress
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: flux
      app.kubernetes.io/name: flux
      app.kubernetes.io/part-of: flux
      app.kubernetes.io/component: helm-controller
  egress:
    - {}
  ingress:
    # Allow inbound connections
    - ports:
        - port: 9440
        - port: 8080
---
# Source: flux/templates/helm-controller/pdb.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: flux-helm-controller
  namespace: "flux-system"
  labels:
    app.kubernetes.io/instance: flux
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: flux
    app.kubernetes.io/version: 1.0.1
    helm.sh/chart: flux-2.3.12
    app.kubernetes.io/part-of: flux
    app.kubernetes.io/component: helm-controller
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: flux
      app.kubernetes.io/name: flux
      app.kubernetes.io/component: helm-controller
---
# Source: flux/templates/helm-controller/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flux-helm-controller
  namespace: "flux-system"
  labels:
    app.kubernetes.io/instance: flux
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: flux
    app.kubernetes.io/version: 1.0.1
    helm.sh/chart: flux-2.3.12
    app.kubernetes.io/part-of: flux
    app.kubernetes.io/component: helm-controller
automountServiceAccountToken: false
